In [1]:
import numpy as np
import pandas as pd

In [2]:
np.array([1, 2, 3], dtype=np.float64)

array([1., 2., 3.])

In [5]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [6]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [7]:
np.logspace(1, 3, 3)

array([  10.,  100., 1000.])

In [8]:
np.zeros_like([[1, 2, 3], [4, 5, 6]])

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.array([1, 2, 3, 4]).reshape(1, -1)

array([[1, 2, 3, 4]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6])

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack([a, b])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
a = np.array([[1], [2], [3]])

b = np.array([[4], [5], [6]])

np.hstack([a, b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
a = np.array([[1, 2], [3, 4]])

b = np.array([[5, 6]])

np.concatenate([a, b], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
np.split(np.array([1, 2, 3, 4]), 2)

[array([1, 2]), array([3, 4])]

In [23]:
np.array_split(np.array([1, 2, 3, 4, 5]), 2)

[array([1, 2, 3]), array([4, 5])]

In [24]:
np.hsplit(np.array([[1, 2], [3, 4]]), 2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [25]:
np.array_split(np.array([1, 2, 3, 4, 5, 6]), 4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [26]:
np.vsplit(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [27]:
np.split(np.array([1, 2, 3, 4, 5, 6]), [1, 3])

[array([1]), array([2, 3]), array([4, 5, 6])]

In [28]:
np.array([1, 2, 3], dtype=np.int32)

array([1, 2, 3])

In [3]:
np.sort(np.array([[3, 1], [2, 4]]), axis=1)

array([[1, 3],
       [2, 4]])

In [4]:
np.sort(np.array([3, 1, 4, 1]))

array([1, 1, 3, 4])

In [5]:
np.argsort(np.array([3, 1, 4, 1]))

array([1, 3, 0, 2], dtype=int64)

In [6]:
np.argsort(np.array([[3, 1], [2, 4]]), axis=0)

array([[1, 0],
       [0, 1]], dtype=int64)

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1, 2]

6

In [8]:
arr = np.array([10, 20, 30, 40, 50])
arr[-1]

50

In [9]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr[1, 0, 1]

6

In [10]:
arr = np.array([1, 2, 3, 4, 5])
np.where(arr < 3, arr, 10*arr)

array([ 1,  2, 30, 40, 50])

In [11]:
arr = np.array([10, 20, 30, 40, 50])
arr[-1:-6:-1]

array([50, 40, 30, 20, 10])

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[:, 1]

array([2, 5, 8])

In [20]:
arr = np.array([1, 2, 3, 4, 5])
arr[2:5] = [20, 30, 40]

In [21]:
arr

array([ 1,  2, 20, 30, 40])

In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[arr[:, 1] > 2, 1:3]

array([[5, 6],
       [8, 9]])

In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[(arr > 20) & (arr < 70)]

array([30, 40, 50, 60])

In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0, 1, :2]

array([4, 5])

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[(arr[:, 0] > 2)][:, [0, 2]]

array([[4, 6],
       [7, 9]])

In [30]:
arr = np.array([10, 20, 30, 40, 50])
arr[[1, 3, 4]]

array([20, 40, 50])

In [31]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
arr[[0, 2], [1, 0]]

array([2, 5])

In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[[2, 0], 1:]

array([[8, 9],
       [2, 3]])

In [40]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
arr[[1, 3]]

array([[3, 4],
       [7, 8]])

In [42]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr[[0, 1], [1, 2]]

array([20, 60])

In [43]:
arr = np.array([10, 20, 30, 40, 50])
arr[[-3, -1]]

array([30, 50])

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr[:, [0, 2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [3]:
np.array([1,2], ndmin=3)

array([[[1, 2]]])

In [2]:
a = np.array([1, 2, 3])

In [3]:
b = 2

In [4]:
a * b

array([2, 4, 6])

In [5]:
a = np.array([1, 2, 3])

In [6]:
b = np.array([1])

In [7]:
a + b

array([2, 3, 4])

In [8]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
b = np.array([1, 2, 3])

In [10]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [11]:
a = np.array([1, 2, 3])

In [12]:
b = np.array([[1], [2]])

In [13]:
a+b

array([[2, 3, 4],
       [3, 4, 5]])

In [14]:
a = np.ones((3, 3))
b = np.array([1, 2, 3])
a+b

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [15]:
a = np.array([[1, 2], [3, 4]])
b = 10
a*b

array([[10, 20],
       [30, 40]])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.add(a, b)

array([5, 7, 9])

In [17]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
np.subtract(a, b)

array([ 9, 18, 27])

In [18]:
a = np.array([1, 2, 3])
b = 2
np.multiply(a, b)

array([2, 4, 6])

In [19]:
a = np.array([1, 2, 3])
np.power(a, 3)

array([ 1,  8, 27], dtype=int32)

In [20]:
a = np.array([1, 4, 9])
np.sqrt(a)

array([1., 2., 3.])

In [21]:
a = np.array([-1, -2, 3])
np.abs(a)

array([1, 2, 3])

In [22]:
a = np.array([1, 2, 3, 4, 5])
np.sum(a)

15

In [23]:
np.ndim(np.array([[1, 2], [3, 4]]))

2

In [24]:
np.dot(np.array([1, 2]), np.array([3, 4]))

11

In [26]:
np.reshape(np.array([1, 2, 3, 4]), (2, 2))

array([[1, 2],
       [3, 4]])

In [27]:
np.sum(np.array([[1, 2], [3, 4]]), axis=1)

array([3, 7])

In [28]:
np.std(np.array([1, 1, 1,1, 1]))

0.0